version: "3"
services:
  dhcphelper:
    build: ./dhcphelper
    restart: unless-stopped
    network_mode: "host"
    command: -s 172.31.0.33
    ports:
      - "67:67/udp"
      - "67:67"
    cap_add:
      - NET_ADMIN

  dnscrypt-proxy:
    image: melchor9000/dnscrypt-proxy
    restart: unless-stopped
    dns: 127.0.0.1
    networks:
      backend:
        ipv4_address: 172.31.0.32
    volumes:
      - "./dnscrypt-proxy/config:/etc/dnscrypt-proxy"

  hero-masq:
    build: .
    ports:
      - "3000:3000/tcp"
      - "53:53/udp"
      - "53:53/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
    volumes:
      - "./dnsmasq/conf:/etc/dnsmasq.d/"
      - "./dnsmasq/leases:/var/lib/dnsmasqd/"
    depends_on:
      - dhcphelper
      - dnscrypt-proxy
    environment:
      DNS: 172.31.0.32
    networks:
      backend:
        ipv4_address: 172.31.0.33

networks:
  backend:
    ipam:
      config:
        - subnet: 172.31.0.0/16
